# Release keystore configuration
# Fill in your keystore details below

# Path to the .jks file (relative to android/app/)
RELEASE_STORE_FILE=../../@yicotseng__my-chat-app.jks

# Keystore password
RELEASE_STORE_PASSWORD=3aacca4dae1cdcbfc0af5e0a33c1e292

# Key alias
RELEASE_KEY_ALIAS=257ce0d2d5817acac68b4af3214040ce

# Key password (usually same as store password)
RELEASE_KEY_PASSWORD=37c29978a95f109e1ea42500827c4ef4
